name: Check Code Formatting
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]
jobs:
  test:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier
      - name: Lint
        run: npm run lint